# [PRACTICA DE NUMPY](https://joserzapata.github.io/courses/python-ciencia-datos/numpy/)
## [Curso Python para Ciencia de datos](https://joserzapata.github.io/courses/python-ciencia-datos/)
### Por Jose R. Zapata - https://joserzapata.github.io/

<div class="alert alert-success">

<b>NOTA:</b> Realizar Primero los ejercicios y luego revisar las soluciones propuestas.

[Solucion Ejercicios Numpy - click para abrir](https://joserzapata.github.io/courses/python-ciencia-datos/numpy/2-practica_numpy-solucion/)

</div>

Los arreglos de numpy son la base de la computación científica en Python
- los dataframes de pandas para análisis de datos (Numpy era la unica base hasta pandas 1.5.3)
- los datos de entrada o salida para hacer Machine Learning con scikit-learn son arreglos de numpy

**Nota:** Es importante familiarizarse con el manejo de arreglos de numpy para poder hacer ciencia de datos con Python e identificar cuando usar un arreglo de numpy o un dataframe de pandas.

**Importe NumPy como np**

In [2]:
import numpy as np 

**Cree un arreglo de ceros de 10 elementos**

In [ ]:
    # Copie su código aqui

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Cree un arreglo de unos de 10 elementos**

In [ ]:
# Copie su código aqui

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Cree un arreglo de cincos de 10 elementos**

In [ ]:
# Copie su código aqui

In [7]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Cree un arreglo de números enteros Del 10 al 50 (incluido)**

In [ ]:
# Copie su código aqui

In [9]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Cree un arreglo de los números enteros pares Del 10 al 50 (incluidos)**

In [ ]:
# Copie su código aqui

In [10]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Crear una matrix de 3x3 con valores del 0 al 8 (incluido)**

In [ ]:
# Copie su código aqui

In [12]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Crear la matriz identidad de 3x3**

In [ ]:
# Copie su código aqui

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Use NumPy para generar un numero aleatorio entre 0 y 1**

In [ ]:
# Copie su código aqui

In [14]:
np.random.rand(1)

array([0.0269818])

**Use NumPy para generar un arreglo de 25 números aleatorios que sean de la distribucion normal estandar**

In [ ]:
# Copie su código aqui

In [30]:
np.random.randn(25)

array([ 0.23973632,  0.96489496,  1.54943012, -0.30297486,  0.82089133,
        0.68707788,  1.11852658,  0.94142267,  0.84365593,  0.46954158,
       -1.65734742,  0.50083574, -1.07118723,  0.00756177, -0.81317784,
        0.2077042 ,  0.29154762,  1.42263063, -0.72185137, -1.80144922,
       -0.60890551, -0.05652624, -1.11913933, -0.30507868,  0.07870981])

**Cree un arreglo de 20 elementos linealmente espaciados entre 0 y 1:**

In [ ]:
# Copie su código aqui

In [33]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**Indexacion y seleccion con Numpy**

Crear una matriz con numeros del 1 al 25 y que tenga forma de 5x5



In [ ]:
# Copie su código aqui


In [41]:
matriz = np.arange(1,26).reshape(5,5)
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


replique los resultados que siguen:


In [ ]:
# Copie su código aqui

In [ ]:
print(matriz[2:,1:])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# Copie su código aqui

In [46]:
print(matriz[3,4])

20


In [ ]:
# Copie su código aqui

In [52]:
print(matriz[:3,1:2])

[[ 2]
 [ 7]
 [12]]


In [ ]:
# Copie su código aqui

In [51]:
print(matriz[4:,:5])

[[21 22 23 24 25]]


In [ ]:
# Copie su código aqui

In [60]:
print(matriz[3:5,:])


[[16 17 18 19 20]
 [21 22 23 24 25]]


**Obtenga la suma de todos los valores de la matriz**

In [ ]:
# Copie su código aqui

In [61]:
print(matriz.sum())

325


**Obtenga la desviación estándar de los valores de la matriz**

In [ ]:
# Copie su código aqui

In [62]:
print(matriz.std())

7.211102550927978


**Obtener la suma de cada una de las columnas de la matriz**

In [ ]:
# Copie su código aqui

In [63]:
print(matriz.sum(axis=0))

[55 60 65 70 75]


## Referencia

https://joserzapata.github.io/courses/python-ciencia-datos/numpy/